### ISSUE TITLE
Can we reduce files?

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/eslint-config-taskcluster#1]
Needing to have 4 dependencies:

```
    "babel-eslint": "^6.0.0",
    "mocha-eslint": "^2.0.1",
    "eslint-config-taskcluster": "^1.0.0",
    "eslint-plugin-taskcluster": "^1.0.0"
```

And two files: `test/lint_test.js` and `.eslintrc` is way too much to drag around...

Perhaps we can specify the config inside `test/lint_test.js`...
Or maybe we can make extension to taskcluster-lib-testing.. that depends on all this and just requires us to add a file `test/lint_test.js` and inside it do `require('taskcluster-lib-testing').lint('src', 'test')`;
Or something like that ?

**Comment by jonasfj** [comment]
@imbstack I'm not sure what we can do... Just saying maybe we should consider reducing the overhead...

It's a lot of duplication, we have to copy around... Which in the long run creates a lot of legacy...

**Comment by imbstack** [comment]
I agree it's annoying how much there is to drag around. Not sure which is the best way to go about fixing it yet either. We can think on it for a bit.
